---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv23
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs/pv23
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv24
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs/pv24
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Delete
