# use CluserIP service
# enable Ingress

service:
  type: ClusterIP

httpRoute:
  enabled: true
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
  hostnames:
    - wordpress.clusterx.qedzone.ro
