apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv20
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs/pv20
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv21
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs/pv21
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv22
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs/pv22
    server: nfsserver.local
  persistentVolumeReclaimPolicy: Delete
